export const SWITCH_PRODUCTS_CART_SIDEBAR = "SWITCH_PRODUCTS_CART_SIDEBAR";
export const ADD_NEW_PRODUCT_TO_CART = "ADD_NEW_PRODUCT_TO_CART";
export const REMOVE_PRODUCTS_FROM_CART = "REMOVE_PRODUCTS_FROM_CART";
export const INCREASE_AMOUNT_OF_PRODUCTS = "INCREASE_AMOUNT_OF_PRODUCTS";
export const DECREASE_AMOUNT_OF_PRODUCTS = "DECREASE_AMOUNT_OF_PRODUCTS";
export const REMOVE_SINGLE_PRODUCT_FROM_CART = "REMOVE_SINGLE_PRODUCT_FROM_CART";